apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleepy
  labels:
    app: sleepy
spec:
  selector:
    matchLabels:
      app: sleepy
  replicas: 1
  template:
    metadata:
      labels:
        app: sleepy
    spec:
      containers:
        - name: sleepy
          image: 'docker.io/sholly/sleepy:1.0'
          livenessProbe:
            exec:
              command:
                - cat 
                - /tmp/health
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
